### PR TITLE
Update id3.py

### PR DESCRIPTION
**Pull request by TheBengineer**
Catch the vase where the Genre field is empty.

### CODE REVIEW

**Comment by TheBengineer** [comment]
This fixes Issue 12
https://github.com/artcom-net/mp3-tagger/issues/12

**Comment by kk-hiraskar** [comment]
> This fixes Issue 12
> #12

This will handle only if genre is empty..  
what about if it is having string instead of integer?

I am having many mp3 files, where genre is with some other strings.

**Comment by kk-hiraskar** [comment]
Already issue is fixed and committed here in github: [fix diff](https://github.com/artcom-net/mp3-tagger/commit/dc6f0df5bcf335254956131a21644b0a0510dc32#diff-58bb095604eba5afd642ba3244fdfcc05ebf7e8314e8ead552f927a4f8301e97)

please release it on https://pypi.org/project/mp3-tagger/

**Comment by TheBengineer** [comment]
Closed because fixed.

**Pull request closed without merging**
